
    create table Person (
       id bigint generated by default as identity,
        age integer,
        name varchar(255),
        primary key (id)
    )

    create table Person (
       id bigint generated by default as identity,
        age integer,
        name varchar(255),
        primary key (id)
    )

    create table Person (
       id bigint generated by default as identity,
        age integer,
        name varchar(255),
        primary key (id)
    )

    create table Person (
       id bigint generated by default as identity,
        age integer,
        name varchar(255),
        primary key (id)
    )
